name: Appium Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-12
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Set up Appium
      run: |
        npm install -g appium@next
        appium driver install uiautomator2
        appium &

    - name: Install Android SDK packages
      run: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-29;default;x86_64" "emulator"
        echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n test_avd -k "system-images;android-29;default;x86_64" --device "Nexus 6"
    
    - name: Start Emulator
      run: |
        $ANDROID_HOME/emulator/emulator -avd test_avd -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect &
        $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
        sleep 10
        $ANDROID_HOME/platform-tools/adb shell input keyevent 82

    - name: Run Tests
      run: mvn test
